version: "3"
services:
  nginx:
    image: nginx:alpine
    restart: always
    container_name: thinkcmf-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf/default.conf:/etc/conf/default.conf
    networks:
      - web
  php-fpm:
    image: thinkcmfpro/thinkcmf:latest
    restart: always
    container_name: thinkcmf-php-fpm
    volumes:
      - ./:/var/www/html/:rw
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=thinkcmf
      - DATABASE_DATABASE=thinkcmf
    networks:
      - web
  mysql:
    image: mysql:5.7 
    restart: always
    container_name: thinkcmf-mysql
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=thinkcmf
    networks:
      - web
  redis:
    image: redis:6.0.12-alpine
    restart: always
    container_name: thinkcmf-redis
    volumes:
      - ./docker/redis/data:/data
    networks:
      - web
  adminer:
    image: adminer
    container_name: thinkcmf-mysql-manage
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DEFAULT_USER=thinkcmf
    ports:
      - "1000:8080"
    depends_on:
      - mysql
    networks:
      - web
    restart: always

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: thinkcmf-redis-manage
    environment:
      - TZ=Asia/Shanghai
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - ADMIN_USER=thinkcmf
      - ADMIN_PASS=thinkcmf
    ports:
      - "2000:80"
    depends_on:
      - redis
    networks:
      - web
    restart: always
networks:
  web: